- name: Build and push Docker image to Docker Hub
  hosts: localhost
  tasks:
    - name: Copy Dockerfile to build context directory
      copy:
        src: Dockerfile
        dest: /tmp/build-context/

    - name: Build Docker image using Dockerfile
      docker_image:
        path: /tmp/build-context/
        src: /var/lib/jenkins/workspace/EdurekaProject1Package/target/
        name: "krischai81/edureka-tomcat"
        tag: "latest"
        
    - name: Login to Docker Hub
      docker_login:
        username: "krischai81"
        password: "G1ng3rG@rlic2022#"
        registry_url: https://hub.docker.com/

    - name: Push Docker image to Docker Hub
      docker_image:
        name: "krischai81/edureka-tomcat"
        tag: "latest"
        push: yes
