---
- hosts: localhost
  collections:
    - community.docker
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python
    docker_image_name: Edureka-tomcat
    docker_hub_username: krischai81
    docker_hub_password: G1ng3rG@rlic2022#
  tasks:
    - name: Log in to Docker Hub
      docker_login:
        #registry_url: https://hub.docker.com/
        username: "krischai81"
        password: "G1ng3rG@rlic2022#"
     
    - name: Tag Docker Image
      docker_image:
        name: "Edureka-tomcat"
        tag: latest
        repository: "krischai81/edureka-tomcat"

    - name: Push Docker Image to Docker Hub
      docker_image:
        name: "krischai81/edureka-tomcat:latest"
        push: yes
