apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
spec:
  containers:
  - name: tomcat-container
    image: tomcat:9.0-alpine
    ports:
      - containerPort: 8082
    volumeMounts:
      - name: webapps
        mountPath: /usr/local/tomcat/webapps
  volumes:
  - name: webapps
    hostPath:
      path: /var/lib/jenkins/workspace/EdurekaProject1Package/target/
      type: File
